apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-feed-v2
  labels:
    commit: bde1341a8bf20e3c9fb6cf5ab481c05d5d420d34
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitter-feed
  template:
    metadata:
      labels:
        app: twitter-feed
        commit: bde1341a8bf20e3c9fb6cf5ab481c05d5d420d34
        color: green
    spec:
      containers:
      - name: twitter-feed
        image: ${DOCKER_REGISTRY}/twitter-feed:MASTER-bde1341a8bf20e3c9fb6cf5ab481c05d5d420d34}
        imagePullPolicy: Always
        ports:
        - name: twitter-feed
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: podinfo
            mountPath: /tmp
            readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-feed
  labels:
    app: twitter-feed
    commit: bde1341a8bf20e3c9fb6cf5ab481c05d5d420d34
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: twitter-feed
    color: green
  type: ClusterIP
---
